app = 'pdp-dashboard-giorgi'
primary_region = 'cdg'

# Public Configuration
[env]
  GOOGLE_SHEET_NAME = "ADHD BP & HR"
  MED_START_DATE = "2025-12-08"
  GOOGLE_APPLICATION_CREDENTIALS = ".secrets/personal-data-platform.json"
  # Toggles
  INGESTION_ENABLED = "true"
  VALIDATION_ENABLED = "true"
  PROCESSING_ENABLED = "true"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256

# Override the Dockerfile CMD to run Streamlit instead of the pipeline
[experimental]
  cmd = ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]